// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlertController from "./alert_controller"
application.register("alert", AlertController)

import CalendarioController from "./calendario_controller"
application.register("calendario", CalendarioController)

import ChartController from "./chart_controller"
application.register("chart", ChartController)

import ChatController from "./chat_controller"
application.register("chat", ChatController)

import DashboardController from "./dashboard_controller"
application.register("dashboard", DashboardController)

import DesktopNavController from "./desktop_nav_controller"
application.register("desktop-nav", DesktopNavController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import FormController from "./form_controller"
application.register("form", FormController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LoginController from "./login_controller"
application.register("login", LoginController)

import LoginMessageTimeController from "./login_message_time_controller"
application.register("login-message-time", LoginMessageTimeController)

import MessageLoginController from "./message_login_controller"
application.register("message-login", MessageLoginController)

import MobileNavController from "./mobile_nav_controller"
application.register("mobile-nav", MobileNavController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import NavDropdownController from "./nav_dropdown_controller"
application.register("nav-dropdown", NavDropdownController)

import NotificationController from "./notification_controller"
application.register("notification", NotificationController)

import NotificationsController from "./notifications_controller"
application.register("notifications", NotificationsController)

import ProfileFormController from "./profile_form_controller"
application.register("profile-form", ProfileFormController)

import Select2UsersController from "./select2_users_controller"
application.register("select2-users", Select2UsersController)

import ServiceAlertController from "./service_alert_controller"
application.register("service-alert", ServiceAlertController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import SweetAlertController from "./sweet_alert_controller"
application.register("sweet-alert", SweetAlertController)

import ThemeController from "./theme_controller"
application.register("theme", ThemeController)

import ViewModeController from "./view_mode_controller"
application.register("view-mode", ViewModeController)
