// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlertController from "./alert_controller"
application.register("alert", AlertController)

import ChartController from "./chart_controller"
application.register("chart", ChartController)

import FormController from "./form_controller"
application.register("form", FormController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LoginController from "./login_controller"
application.register("login", LoginController)

import LoginMessageTimeController from "./login_message_time_controller"
application.register("login-message-time", LoginMessageTimeController)

import MessageLoginController from "./message_login_controller"
application.register("message-login", MessageLoginController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import NavDropdownController from "./nav_dropdown_controller"
application.register("nav-dropdown", NavDropdownController)

import ProfileFormController from "./profile_form_controller"
application.register("profile-form", ProfileFormController)

import ServiceAlertController from "./service_alert_controller"
application.register("service-alert", ServiceAlertController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import SweetAlertController from "./sweet_alert_controller"
application.register("sweet-alert", SweetAlertController)
