require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/action_permissions", type: :request do
  include Devise::Test::IntegrationHelpers

  
  # This should return the minimal set of attributes required to create a valid
  # ActionPermission. As you add validations to ActionPermission, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ActionPermission.create! valid_attributes
      get action_permissions_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      action_permission = ActionPermission.create! valid_attributes
      get action_permission_url(action_permission)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_action_permission_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      action_permission = ActionPermission.create! valid_attributes
      get edit_action_permission_url(action_permission)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ActionPermission" do
        expect {
          post action_permissions_url, params: { action_permission: valid_attributes }
        }.to change(ActionPermission, :count).by(1)
      end

      it "redirects to the created action_permission" do
        post action_permissions_url, params: { action_permission: valid_attributes }
        expect(response).to redirect_to(action_permission_url(ActionPermission.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ActionPermission" do
        expect {
          post action_permissions_url, params: { action_permission: invalid_attributes }
        }.to change(ActionPermission, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post action_permissions_url, params: { action_permission: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested action_permission" do
        action_permission = ActionPermission.create! valid_attributes
        patch action_permission_url(action_permission), params: { action_permission: new_attributes }
        action_permission.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the action_permission" do
        action_permission = ActionPermission.create! valid_attributes
        patch action_permission_url(action_permission), params: { action_permission: new_attributes }
        action_permission.reload
        expect(response).to redirect_to(action_permission_url(action_permission))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        action_permission = ActionPermission.create! valid_attributes
        patch action_permission_url(action_permission), params: { action_permission: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested action_permission" do
      action_permission = ActionPermission.create! valid_attributes
      expect {
        delete action_permission_url(action_permission)
      }.to change(ActionPermission, :count).by(-1)
    end

    it "redirects to the action_permissions list" do
      action_permission = ActionPermission.create! valid_attributes
      delete action_permission_url(action_permission)
      expect(response).to redirect_to(action_permissions_url)
    end
  end
end
