require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/controller_permissions", type: :request do
  include Devise::Test::IntegrationHelpers

  
  # This should return the minimal set of attributes required to create a valid
  # ControllerPermission. As you add validations to ControllerPermission, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ControllerPermission.create! valid_attributes
      get controller_permissions_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      controller_permission = ControllerPermission.create! valid_attributes
      get controller_permission_url(controller_permission)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_controller_permission_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      controller_permission = ControllerPermission.create! valid_attributes
      get edit_controller_permission_url(controller_permission)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ControllerPermission" do
        expect {
          post controller_permissions_url, params: { controller_permission: valid_attributes }
        }.to change(ControllerPermission, :count).by(1)
      end

      it "redirects to the created controller_permission" do
        post controller_permissions_url, params: { controller_permission: valid_attributes }
        expect(response).to redirect_to(controller_permission_url(ControllerPermission.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ControllerPermission" do
        expect {
          post controller_permissions_url, params: { controller_permission: invalid_attributes }
        }.to change(ControllerPermission, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post controller_permissions_url, params: { controller_permission: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested controller_permission" do
        controller_permission = ControllerPermission.create! valid_attributes
        patch controller_permission_url(controller_permission), params: { controller_permission: new_attributes }
        controller_permission.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the controller_permission" do
        controller_permission = ControllerPermission.create! valid_attributes
        patch controller_permission_url(controller_permission), params: { controller_permission: new_attributes }
        controller_permission.reload
        expect(response).to redirect_to(controller_permission_url(controller_permission))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        controller_permission = ControllerPermission.create! valid_attributes
        patch controller_permission_url(controller_permission), params: { controller_permission: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested controller_permission" do
      controller_permission = ControllerPermission.create! valid_attributes
      expect {
        delete controller_permission_url(controller_permission)
      }.to change(ControllerPermission, :count).by(-1)
    end

    it "redirects to the controller_permissions list" do
      controller_permission = ControllerPermission.create! valid_attributes
      delete controller_permission_url(controller_permission)
      expect(response).to redirect_to(controller_permissions_url)
    end
  end
end
