require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/create_perfil_permissions", type: :request do
  include Devise::Test::IntegrationHelpers

  
  # This should return the minimal set of attributes required to create a valid
  # CreatePerfilPermission. As you add validations to CreatePerfilPermission, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CreatePerfilPermission.create! valid_attributes
      get create_perfil_permissions_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      create_perfil_permission = CreatePerfilPermission.create! valid_attributes
      get create_perfil_permission_url(create_perfil_permission)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_create_perfil_permission_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      create_perfil_permission = CreatePerfilPermission.create! valid_attributes
      get edit_create_perfil_permission_url(create_perfil_permission)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CreatePerfilPermission" do
        expect {
          post create_perfil_permissions_url, params: { create_perfil_permission: valid_attributes }
        }.to change(CreatePerfilPermission, :count).by(1)
      end

      it "redirects to the created create_perfil_permission" do
        post create_perfil_permissions_url, params: { create_perfil_permission: valid_attributes }
        expect(response).to redirect_to(create_perfil_permission_url(CreatePerfilPermission.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CreatePerfilPermission" do
        expect {
          post create_perfil_permissions_url, params: { create_perfil_permission: invalid_attributes }
        }.to change(CreatePerfilPermission, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post create_perfil_permissions_url, params: { create_perfil_permission: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested create_perfil_permission" do
        create_perfil_permission = CreatePerfilPermission.create! valid_attributes
        patch create_perfil_permission_url(create_perfil_permission), params: { create_perfil_permission: new_attributes }
        create_perfil_permission.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the create_perfil_permission" do
        create_perfil_permission = CreatePerfilPermission.create! valid_attributes
        patch create_perfil_permission_url(create_perfil_permission), params: { create_perfil_permission: new_attributes }
        create_perfil_permission.reload
        expect(response).to redirect_to(create_perfil_permission_url(create_perfil_permission))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        create_perfil_permission = CreatePerfilPermission.create! valid_attributes
        patch create_perfil_permission_url(create_perfil_permission), params: { create_perfil_permission: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested create_perfil_permission" do
      create_perfil_permission = CreatePerfilPermission.create! valid_attributes
      expect {
        delete create_perfil_permission_url(create_perfil_permission)
      }.to change(CreatePerfilPermission, :count).by(-1)
    end

    it "redirects to the create_perfil_permissions list" do
      create_perfil_permission = CreatePerfilPermission.create! valid_attributes
      delete create_perfil_permission_url(create_perfil_permission)
      expect(response).to redirect_to(create_perfil_permissions_url)
    end
  end
end
