require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/perfil_users", type: :request do
  include Devise::Test::IntegrationHelpers

  
  # This should return the minimal set of attributes required to create a valid
  # PerfilUser. As you add validations to PerfilUser, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PerfilUser.create! valid_attributes
      get perfil_users_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      perfil_user = PerfilUser.create! valid_attributes
      get perfil_user_url(perfil_user)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_perfil_user_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      perfil_user = PerfilUser.create! valid_attributes
      get edit_perfil_user_url(perfil_user)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PerfilUser" do
        expect {
          post perfil_users_url, params: { perfil_user: valid_attributes }
        }.to change(PerfilUser, :count).by(1)
      end

      it "redirects to the created perfil_user" do
        post perfil_users_url, params: { perfil_user: valid_attributes }
        expect(response).to redirect_to(perfil_user_url(PerfilUser.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PerfilUser" do
        expect {
          post perfil_users_url, params: { perfil_user: invalid_attributes }
        }.to change(PerfilUser, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post perfil_users_url, params: { perfil_user: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested perfil_user" do
        perfil_user = PerfilUser.create! valid_attributes
        patch perfil_user_url(perfil_user), params: { perfil_user: new_attributes }
        perfil_user.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the perfil_user" do
        perfil_user = PerfilUser.create! valid_attributes
        patch perfil_user_url(perfil_user), params: { perfil_user: new_attributes }
        perfil_user.reload
        expect(response).to redirect_to(perfil_user_url(perfil_user))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        perfil_user = PerfilUser.create! valid_attributes
        patch perfil_user_url(perfil_user), params: { perfil_user: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested perfil_user" do
      perfil_user = PerfilUser.create! valid_attributes
      expect {
        delete perfil_user_url(perfil_user)
      }.to change(PerfilUser, :count).by(-1)
    end

    it "redirects to the perfil_users list" do
      perfil_user = PerfilUser.create! valid_attributes
      delete perfil_user_url(perfil_user)
      expect(response).to redirect_to(perfil_users_url)
    end
  end
end
