require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/perfils", type: :request do
  include Devise::Test::IntegrationHelpers

  
  # This should return the minimal set of attributes required to create a valid
  # Perfil. As you add validations to Perfil, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Perfil.create! valid_attributes
      get perfils_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      perfil = Perfil.create! valid_attributes
      get perfil_url(perfil)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_perfil_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      perfil = Perfil.create! valid_attributes
      get edit_perfil_url(perfil)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Perfil" do
        expect {
          post perfils_url, params: { perfil: valid_attributes }
        }.to change(Perfil, :count).by(1)
      end

      it "redirects to the created perfil" do
        post perfils_url, params: { perfil: valid_attributes }
        expect(response).to redirect_to(perfil_url(Perfil.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Perfil" do
        expect {
          post perfils_url, params: { perfil: invalid_attributes }
        }.to change(Perfil, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post perfils_url, params: { perfil: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested perfil" do
        perfil = Perfil.create! valid_attributes
        patch perfil_url(perfil), params: { perfil: new_attributes }
        perfil.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the perfil" do
        perfil = Perfil.create! valid_attributes
        patch perfil_url(perfil), params: { perfil: new_attributes }
        perfil.reload
        expect(response).to redirect_to(perfil_url(perfil))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        perfil = Perfil.create! valid_attributes
        patch perfil_url(perfil), params: { perfil: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested perfil" do
      perfil = Perfil.create! valid_attributes
      expect {
        delete perfil_url(perfil)
      }.to change(Perfil, :count).by(-1)
    end

    it "redirects to the perfils list" do
      perfil = Perfil.create! valid_attributes
      delete perfil_url(perfil)
      expect(response).to redirect_to(perfils_url)
    end
  end
end
