# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "postgres") %>

development:
  <<: *default
  database: genius360_development

test:
  <<: *default
  database: genius360_test

production:
  <<: *default
  database: genius360_production
  username: <%= ENV['GENIUS360_DATABASE_USERNAME'] %>
  password: <%= ENV['GENIUS360_DATABASE_PASSWORD'] %>
