# Nome da sua aplicação. Usado para configurar containers de forma única.
service: genius360

# Nome da imagem do container.
image: genius360

# Implantar nestes servidores.
servers:
  web:
    hosts:
      - 157.173.201.122 
    labels:
      traefik.enable: true

# Habilita certificação SSL automática via Let's Encrypt e permite múltiplos apps em um único servidor web.
proxy:
  ssl: true
  host: app.example.com

# Credenciais para seu host de imagens.
registry:
  server: registry.contabo.com
  username: pauloribeiro670
  password:
    - KAMAL_REGISTRY_PASSWORD

# Injete variáveis de ambiente nos containers (segredos vêm de .kamal/secrets).
env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true
    RAILS_ENV: production
    DATABASE_URL: postgres://usuario:senha@host:5432/genius360_production

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "/storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64

jobs:
  build:
    cmd: bin/build
  migrate:
    cmd: bin/rails db:migrate
  deploy:
    cmd: bin/deploy
  staging:
    cmd: bin/deploy --staging
  production:
    cmd: bin/deploy --production
  setup:
    cmd: bin/setup
